project:
  type: website
  output-dir: docs

website:
  title: "DHE"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Context
      - href: dhe-model.qmd
        text: Theory
      - href: dhe-scale.qmd
        text: Measurement
      - href: publications.qmd
        text: Research Outputs
      - href: references.qmd
        text: References
    
format:
  html:
    theme: flatly
    css: styles.css
    toc: false